### ISSUE TITLE
SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by yuniers** [gaye/dav#76]
Today I updated to v1.6.5 and when try `node prueba-dav.js ` an error is tried. I use node 0.12.2

```javascript
import debug from 'debug';
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)  
    at Module._compile (module.js:443:25)  
    at Object.Module._extensions..js (module.js:478:10)  
    at Module.load (module.js:355:32)  
    at Function.Module._load (module.js:310:12)  
    at Module.require (module.js:365:17)  
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sosa/Dev/prueba-agenda/prueba-dav.js:1:73)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by gaye** [comment]
@yuniers Are you using the compiled binary dav/dav.js?

**Comment by yuniers** [comment]
@gaye I update it to 1.7.2 and now not have problems but when I catch promise error obtain this  `[Error: Bad status: 503]`

And I not know why because Zimbra server is active and I can access to my calendar from Thunderbird.

```javascript
var dav = require('dav');

var client = new dav.Client(
  new dav.transport.Basic(
    new dav.Credentials({
      username: 'yjsosa',
      password: 'xxx'
    })
  ),
  {
    baseUrl: 'https://correo.estudiantes.uci.cu'
  }
);
 
var req = dav.request.basic({
  method: 'GET'
  // data: 'BEGIN:VCALENDAR\nEND:VCALENDAR',
  // etag: '12345'
});
 
// req instanceof dav.Request
 
client.send(req, '/home/yjsosa@estudiantes.uci.cu/Calendar')
.then(function(response) {
	console.log(response)
  // response instanceof XMLHttpRequest
})
.catch(function(reason){
	console.log(reason)
});
```

**Comment by gaye** [comment]
@yuniers That just means that you can't perform a GET request on that url. Have you tried using the higher-level api https://github.com/gaye/dav#example-usage which goes through the whole caldav setup flow?

**Comment by yuniers** [comment]
@gaye Just I achieved get the data, the problem is the certificate (it is auto signed).
I want support to CalDAV on node and need a CalDav server (fennel) and a package that parse the data.
I'm beginner on that and soon will study more on it.

**Comment by gaye** [comment]
Ok! I'm going to close this issue since I think things are working as they're supposed to. Feel free to email if you need some general guidance.
